### PR TITLE
Use `lldb` to launch macOS applications

### LINKED ISSUE #47: macOS app entitlements issue
Hello,

I'm having problems running a macOS app that needs specific entitlements for calendar access. The project runs perfectly in Xcode and I can request calendar permissions. When using sweetpad the request authorisation option doesn't work I get the error in the Console.app:

```
Prompting policy for hardened runtime; service: kTCCServiceCalendar requires entitlement com.apple.security.personal-information.calendars but it is missing
```

I have the entitlements file in my project root and tried add the build argument to `settings.json`:

```json
    "sweetpad.build.args": [
      "-skipMacroValidation",
       "CODE_SIGN_ENTITLEMENTS=MyApp/MyApp.entitlements"
    ],
```

While this adds the argument this doesn't work either. ~Looking at the Xcode Build logs it appears Xcode is signing the macOS app due to the hardened runtime/app sandbox.~

I know the project is correctly configured as it works perfectly in Xcode so I assume this is an xcodebuild/signing issue.

~How can I ensure my app is code-signed when using sweetpad?~

**Update:**

The issue relates to how the macOS apps launch as a sub-process of vscode. It appears that the launch process (Vscode) is expected to have the entitlements that are required for the built application. This is likely because of the way macOS builds are launched from the integrated terminal.  

Launching the app build from the system terminal or via `open` commends resolves the issue but then then there is no way to capture `stdout` and `stderror`. 

One solution I've found that works and meets the limitations above is to use `lldb` to "launch" the app and attach a debugging session. While the debugging session is a side effect here, the `lldb` process can launch the app without it being treated as a sub-process, therefore resolving the entitlements issues as well as capturing `stderr` and `stdout` which is needed for vscode integration.

The downside is that you have to launch with a debug session.  That said I don't see this as a limitation as that is what most developers expect when building and running anyway. 

I propose a new build and debug option (additive change) that can be used which in turn resolves these issues for macOS apps that require entitlements.

### PR DESCRIPTION
**Pull request by cameroncooke**
Fixes https://github.com/sweetpad-dev/sweetpad/issues/47

### CODE REVIEW

**Comment by cameroncooke** [comment]
Sorry for the previous PR originally I thought the issue was a code-signing one and went down a rabbit hole. This fix is much simpler and directly fixes my issues.

**Comment by cameroncooke** [comment]
Only, problem I'm seeing with this is that we lose the stderr and stdout.  I could open the executable directly instead of app bundle and this would open a external terminal session which would would show stdout and stderr but this isn't a nice solution as it takes you out of vscode.

**Comment by cameroncooke** [comment]
Ok, one solution that works is to use `lldb` instead of `open` or executing the application directly. This mirrors Xcode's "Run" (Cmd+R) action which builds, run and attaches a debugger. While this is a change in behaviour it's actually with iOS/macOS developers would expect Run to do anyway. 

I would also suggest the same is done for apps running in the iOS simulator. Having to run and then later attach the debugger is problematic for debugging events that happen at launch time. Though this PR doesn't make that change.

**Comment by hyzyla** [comment]
For some reason, the version with the LLDB debugger doesn't work for me. Maybe I should give it a chance tomorrow.

Also, I’ve found a way to redirect stdout, but I haven't tried how it would work in vscode:
```shell
open -W  --stdout $(tty) /Users/hyzyla/Library/Developer/Xcode/DerivedData/ControlRoom-gdvrildvemgjaiameavxoegdskby/Build/Products/Debug/Control\ Room.app/ 
```

**Comment by cameroncooke** [comment]
That's interesting, I personally like the launching with debug session option as this not only fixes the issues I was having it's also representative to how Xcode works when running the app. It always starts a debug session, this was already a pain point for me using this library having to manually attach the debugger.

@hyzyla what error did you see when trying to launch the app using lldb?

**Comment by cameroncooke** [comment]
> For some reason, the version with the LLDB debugger doesn't work for me. Maybe I should give it a chance tomorrow.
> 
> Also, I’ve found a way to redirect stdout, but I haven't tried how it would work in vscode:
> 
> ```shell
> open -W  --stdout $(tty) /Users/hyzyla/Library/Developer/Xcode/DerivedData/ControlRoom-gdvrildvemgjaiameavxoegdskby/Build/Products/Debug/Control\ Room.app/ 
> ```

This looks like a great quick fix, maybe we could add new build options (run with debugger) and run (without debugging) that way we can choose.

**Comment by cameroncooke** [comment]
Technically if you honour the selected scheme sweetpad should attach debugger if the scheme has that option enabled:

Screenshot 2024-10-08 at 09 50 18

Currently the run command ignores this. Personally I think it should honour this and use lldb as per my PR if this option is enabled in the scheme otherwise use the `open` command. This should be the same for running apps in simulator too.

**Comment by cameroncooke** [comment]
I am going to close this, for now, will have another PR up shortly that doesn't break existing functionality

**Pull request closed without merging**
